//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringOperations")]
public interface IStringOperations
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringOperations/GetSearchStringContainsCount", ReplyAction="http://tempuri.org/IStringOperations/GetSearchStringContainsCountResponse")]
    int GetSearchStringContainsCount(string searchString, string containsString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringOperations/GetSearchStringContainsCount", ReplyAction="http://tempuri.org/IStringOperations/GetSearchStringContainsCountResponse")]
    System.Threading.Tasks.Task<int> GetSearchStringContainsCountAsync(string searchString, string containsString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringOperationsChannel : IStringOperations, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringOperationsClient : System.ServiceModel.ClientBase<IStringOperations>, IStringOperations
{
    
    public StringOperationsClient()
    {
    }
    
    public StringOperationsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringOperationsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetSearchStringContainsCount(string searchString, string containsString)
    {
        return base.Channel.GetSearchStringContainsCount(searchString, containsString);
    }
    
    public System.Threading.Tasks.Task<int> GetSearchStringContainsCountAsync(string searchString, string containsString)
    {
        return base.Channel.GetSearchStringContainsCountAsync(searchString, containsString);
    }
}